### ISSUE TITLE
Setup Tailwind CSS

### ISSUE THREAD

**Issue by geoffturk** [MurmurationsNetwork/MurmurationsProfileGeneratorV2#5]
- [x] [Add Tailwind](https://remix.run/docs/en/v1/guides/styling#tailwind-css)
- [x] Set up automated CSS build/generate scripts for dev/online
- [x] Add a `className` to one of the form elements (e.g., `<select>`) and create a [custom class](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply) for it (e.g., change the background and font colors) just to test it out

**Comment by TingSyuanWang** [comment]
Reference: [Tailwind official website - remix installation](https://tailwindcss.com/docs/guides/remix)
