### ISSUE TITLE
Implement authentication and set up users data storage

### ISSUE THREAD

**Issue by geoffturk** [MurmurationsNetwork/MurmurationsProfileGeneratorV2#7]
The data storage requirements for MPG are simple, so the aim is to rely on a distributed key-value store instead of a database. We'll use Cloudflare Workers KV as the solution, through its [API](https://api.cloudflare.com/#workers-kv-namespace-properties).

MPG users will authenticate with an email address and password, so a hash of the email address can be used to generate a unique ID for each user, which will be the key. The value object will include:
- `password` (string) - hashed password - hashed using `brcryptjs`
- `last_login` (number) - last time the user logged in - Unix timestamp
- `profiles` (array of ~strings~objects) - the list of JSON Schema profile instances created by and stored for the user

The Remix docs have a good example of a [do-it-yourself solution for authentication](https://remix.run/docs/en/v1/tutorials/jokes#authentication). So we can try rolling our own solution using that example, or we could go with a package like [`remix-auth`](https://github.com/sergiodxa/remix-auth) and its associated [Form Strategy](https://github.com/sergiodxa/remix-auth-form).

**Comment by TingSyuanWang** [comment]
Reference:
https://remix.run/docs/en/v1/guides/data-loading#cloudflare-kv

**Comment by geoffturk** [comment]
For hashing, use SHA-256 via this native browser implementation (see the second example that produces a hex string):  
https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest#examples

**Comment by geoffturk** [comment]
# KV Store - MPG Data Model

## Users

### Key

The key is simply a SHA256 hash of the users email address:

`dude@dev.null => 5e64eab91e34c4d6eddc1f515f9ce81dea8238249f0946d40e3fc9ca22b7031a`

### Value

The value is a JSON object that contains the following properties:

- `password` (string) - hashed password - hashed using `brcryptjs`
- `last_login` (number) - last time the user logged in - Unix timestamp
- `profiles` (array of strings) - the list of JSON Schema profile instances created by and stored for the user - each string is a SHA256 hash of the profile instance

## Profiles

### Key

The key is a SHA256 hash of the profile:

```
{
  "linked_schemas": [
    "test_schema-v2.0.0"
  ],
  "name": "The Dude",
  "latitude": 1,
  "longitude": 1
}

=> 48bbf64dff485af6e422fef5f45b41b75a06fc645e7c20da1ddd8a041605331c
```

> Note that the example above includes a newline (`\n`) character at the end of the file, which is included as input in the hash calculation.

### Value

The value is just the profile itself:


```
{
  "linked_schemas": [
    "test_schema-v2.0.0"
  ],
  "name": "The Dude",
  "latitude": 1,
  "longitude": 1
}
```

## Profiles Array

The `profiles` array in the User record will keep track of each user's profiles. This array will need to be updated for each of these scenarios:

1) The user adds a new profile
2) The user deletes a profile
3) The user changes a profile

The first two are obvious, but the third less so, since in a regular database the key that identifies the record would normally not change. However, in this case, the key will always change because any change to a profile will always result in a different hash. So when a profile is changed, the old hash is removed from the `profiles` array and the new hash is added.
